### ISSUE TITLE
npm start in client returns undefined property error

### ISSUE THREAD

**Issue by julianwagle** [FredericHeem/starhackit#579] opened 2021-08-04 20:24 UTC
Following through quickstart tutorial here: https://fredericheem.gitbook.io/starhackit/getting-started/quickstart

The backend fired up fine and I had cd'd into the client dir and successfully ran npm install. However, npm start returned with the following error:

> starhackit-ui@10.14.0 start /.../myproj/client
> webpack serve --config webpack.dev.js --open

[webpack-cli] TypeError: Cannot read property 'overrides' of undefined
    at module.exports (/.../myproj/client/webpack.config.js:103:13)
    at /.../myproj/client/node_modules/webpack-cli/lib/webpack-cli.js:792:43
    at Array.map (<anonymous>)
    at evaluateConfig (/.../myproj/client/node_modules/webpack-cli/lib/webpack-cli.js:784:24)
    at WebpackCLI.resolveConfig (/.../myproj/client/node_modules/webpack-cli/lib/webpack-cli.js:868:47)
    at async WebpackCLI.createCompiler (/.../myproj/client/node_modules/webpack-cli/lib/webpack-cli.js:1157:22)
    at async Command.<anonymous> (/.../myproj/client/node_modules/@webpack-cli/serve/lib/index.js:103:30)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/.../myproj/client/node_modules/webpack-cli/lib/webpack-cli.js:708:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! starhackit-ui@10.14.0 start: `webpack serve --config webpack.dev.js --open`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the starhackit-ui@10.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2021-08-04T19_46_08_454Z-debug.log

I did a simple search through the dirs of the project and found that the var 'overrides' was referenced two other times in webpack.dev.js and webpack.prod.js in the variables 'const webpackDevConfig' and 'const webpackProdConfig' respectively. 

I don't have a solution to this, I simply downloaded an older version and it fired up without a problem. Looking at the updates you've made in the last year, I'm thinking the problem likely lies in either the package.json changes made to the web pack config or. in the. refactoring you did to the webpack.config.js. file

**Comment by FredericHeem** [comment] 2021-08-05 15:21
Thanks for the feedback,  a new release has been published. Please let me know and close the issue if the problem is gone.

**Closed** 2021-08-06 14:53 UTC
